# Generated by Django 3.1.4 on 2020-12-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20201225_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
