# Generated by Django 3.1.4 on 2021-01-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_product_out_of_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='first_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
